<?php
echo '<!DOCTYPE html>';
echo '<html style="font-size: 16px;">';
echo '<head>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta charset="utf-8">';
echo '<meta name="keywords" content="SMK ​MADINATULQURANBoarding School, ​Dukungan Industri​, ​Fasilitas&nbsp;SMK MADINATULQURAN:">';
echo '<meta name="description" content="">';
echo '<meta name="page_type" content="np-template-header-footer-from-plugin">';
echo '<title>Tentang</title>';
echo '<link rel="stylesheet" href="nicepage.css" media="screen">';
echo '<link rel="stylesheet" href="Tentang.css" media="screen">';
echo '<script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>';
echo '<script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>';
echo '<meta name="generator" content="Nicepage 4.2.6, nicepage.com">';
echo '<link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<script type="application/ld+json">{';
echo '"@context": "http://schema.org",';
echo '"@type": "Organization",';
echo '"name": "",';
echo '"logo": "images/logoSMKMQ.png"';
echo '}</script>';
echo '<meta name="theme-color" content="#478ac9">';
echo '<meta property="og:title" content="Tentang">';
echo '<meta property="og:type" content="website">';
echo '</head>';
echo '<body data-home-page="Tentang.html" data-home-page-title="Tentang" class="u-body"><header class="u-clearfix u-header u-header" id="sec-ff60"><div class="u-clearfix u-sheet u-sheet-1">';
echo '<a href="https://nicepage.com" class="u-image u-logo u-image-1" data-image-width="889" data-image-height="889">';
echo '<img src="images/logoSMKMQ.png" class="u-logo-image u-logo-image-1">';
echo '</a>';
echo '<p class="u-text u-text-custom-color-1 u-text-default u-text-1">SMK<br>Madinatul<br>Quran';
echo '</p>';
echo '<nav class="u-menu u-menu-dropdown u-offcanvas u-menu-1">';
echo '<div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;">';
echo '<a class="u-button-style u-custom-active-border-color u-custom-active-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-hover-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">';
echo '<svg viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>';
echo '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><symbol id="menu-hamburger" viewBox="0 0 16 16" style="width: 16px; height: 16px;"><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>';
echo '</symbol>';
echo '</defs></svg>';
echo '</a>';
echo '</div>';
echo '<div class="u-custom-menu u-nav-container">';
echo '<ul class="u-nav u-spacing-30 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-border-2 u-border-active-custom-color-2 u-border-hover-custom-color-2 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-custom-color-2 u-text-custom-color-1 u-text-hover-custom-color-2" style="padding: 10px 12px;">Tentang</a>';
echo '</li><li class="u-nav-item"><a class="u-border-2 u-border-active-custom-color-2 u-border-hover-custom-color-2 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-custom-color-2 u-text-custom-color-1 u-text-hover-custom-color-2" style="padding: 10px 12px;">Kurikulum</a>';
echo '</li><li class="u-nav-item"><a class="u-border-2 u-border-active-custom-color-2 u-border-hover-custom-color-2 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-custom-color-2 u-text-custom-color-1 u-text-hover-custom-color-2" style="padding: 10px 12px;">Galeri</a>';
echo '</li><li class="u-nav-item"><a class="u-border-2 u-border-active-custom-color-2 u-border-hover-custom-color-2 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-custom-color-2 u-text-custom-color-1 u-text-hover-custom-color-2" style="padding: 10px 12px;">Berita</a>';
echo '</li><li class="u-nav-item"><a class="u-border-2 u-border-active-custom-color-2 u-border-hover-custom-color-2 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-custom-color-2 u-text-custom-color-1 u-text-hover-custom-color-2" style="padding: 10px 12px;">Prakerin</a>';
echo '</li></ul>';
echo '</div>';
echo '<div class="u-custom-menu u-nav-container-collapse">';
echo '<div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">';
echo '<div class="u-inner-container-layout u-sidenav-overflow">';
echo '<div class="u-menu-close"></div>';
echo '<ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 12px;">Tentang</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 12px;">Kurikulum</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 12px;">Galeri</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 12px;">Berita</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 12px;">Prakerin</a>';
echo '</li></ul>';
echo '</div>';
echo '</div>';
echo '<div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>';
echo '</div>';
echo '</nav>';
echo '</div></header>';
echo '<section class="u-clearfix u-section-1" src="" id="carousel_3011">';
echo '<div class="u-clearfix u-sheet u-sheet-1">';
echo '<div class="u-custom-color-1 u-expanded-width-xs u-shape u-shape-rectangle u-shape-1"></div>';
echo '<img class="u-image u-image-1" src="images/Desktop-1-1024x626.png" data-image-width="1024" data-image-height="626">';
echo '<div class="u-align-left u-container-style u-group u-right-0 u-white u-group-1">';
echo '<div class="u-container-layout u-container-layout-1">';
echo '<h2 class="u-text u-text-1">SMK ​MADINATULQURAN<br>Boarding School';
echo '</h2>';
echo '<p class="u-text u-text-2"> Sekolah Menengah Kejuruan MADINATULQURAN atau SMK MQ adalah salah satu sekolah di Kecamatan Jonggol Kabupaten Bogor, Jawa Barat yang beroperasi mulai tahun 2015 dan sudah terakreditasi dari BANSM Kemendikbud.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<section class="u-clearfix u-grey-10 u-section-2" id="carousel_55e6">';
echo '<div class="u-clearfix u-sheet u-sheet-1">';
echo '<div class="u-clearfix u-gutter-20 u-layout-wrap u-layout-wrap-1">';
echo '<div class="u-gutter-0 u-layout" style="">';
echo '<div class="u-layout-row" style="">';
echo '<div class="u-align-left u-container-style u-layout-cell u-radius-15 u-right-cell u-size-15 u-white u-layout-cell-1">';
echo '<div class="u-container-layout u-valign-top u-container-layout-1"><span class="u-file-icon u-icon u-icon-1"><img src="images/864685.png" alt=""></span>';
echo '<h4 class="u-text u-text-default u-text-1"> Diniyyah &amp; Umum</h4>';
echo '<p class="u-text u-text-2"> Sebagai acuan dasar dalam penyelenggaraan Lembaga Pendidikan Sekolah.</p>';
echo '<ul class="u-text u-text-3">';
echo '<li>Tahfidz Alqur’an</li>';
echo '<li>Aqidah</li>';
echo '<li>Adab</li>';
echo '<li>Sirah Nabi</li>';
echo '<li>Fiqih Islam</li>';
echo '<li>Kurikulum Diknas</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="u-align-left u-container-style u-layout-cell u-radius-15 u-right-cell u-size-15 u-white u-layout-cell-2">';
echo '<div class="u-container-layout u-container-layout-2"><span class="u-file-icon u-icon u-icon-2"><img src="images/81460.png" alt=""></span>';
echo '<h4 class="u-text u-text-default u-text-4"> Software Engineer</h4>';
echo '<p class="u-text u-text-5"> Santri RPL (Rekayasa Perangkat Lunak) berfokus mempelajari bagaimana mengembangkan software yang berbasis Web, Mobile dan Dekstop</p>';
echo '<ul class="u-text u-text-6">';
echo '<li> UI/UX Design</li>';
echo '<li>Front End Develop<br>';
echo '</li>';
echo '<li>Back End Develop<br>';
echo '</li>';
echo '<li>Mobile App<br>';
echo '</li>';
echo '<li>Fiqih Islam<br>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="u-align-left u-container-style u-layout-cell u-radius-15 u-right-cell u-size-15 u-white u-layout-cell-3">';
echo '<div class="u-container-layout u-valign-top u-container-layout-3"><span class="u-file-icon u-icon u-icon-3"><img src="images/87125.png" alt=""></span>';
echo '<h4 class="u-text u-text-default u-text-7"> Network Engineer</h4>';
echo '<p class="u-text u-text-8"> Santri yang masuk dalam jurusan TKJ (Teknik Komputer dan Jaringan) akan berfokus mempelajari infastruktur Jaringan Komputer dan Server</p>';
echo '<ul class="u-text u-text-9">';
echo '<li> Cisco, Mikrotik, Ubiquiti<br>';
echo '</li>';
echo '<li>SysAdmin<br>';
echo '</li>';
echo '<li>Network Automation<br>';
echo '</li>';
echo '<li>Cyber Security</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="u-align-left u-container-style u-layout-cell u-radius-15 u-right-cell u-size-15 u-white u-layout-cell-4">';
echo '<div class="u-container-layout u-valign-top u-container-layout-4"><span class="u-file-icon u-icon u-icon-4"><img src="images/1152912.png" alt=""></span>';
echo '<h4 class="u-text u-text-default u-text-10"> Program Unggulan</h4>';
echo '<p class="u-text u-text-11"> Selain belajar tentang IT, santri akan mengikuti program unggulan pada 3 bulan pertama sebagai bekal penunjang sebelum memulai kegiatan belajar mengajar</p>';
echo '<ul class="u-text u-text-12">';
echo '<li> English Camp</li>';
echo '<li>Tahfidz Camp</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<section class="u-align-center u-clearfix u-section-3" id="sec-66bf">';
echo '<div class="u-clearfix u-sheet u-sheet-1">';
echo '<h2 class="u-text u-text-default u-text-1"> Dukungan Industri<span style="font-weight: 700;"></span>';
echo '</h2>';
echo '<div class="u-expanded-width u-list u-list-1">';
echo '<div class="u-repeater u-repeater-1">';
echo '<div class="u-container-style u-list-item u-repeater-item">';
echo '<div class="u-container-layout u-similar-container u-valign-top u-container-layout-1">';
echo '<img alt="" class="u-expanded-width-xs u-image u-image-contain u-image-default u-image-1" data-image-width="379" data-image-height="133" src="images/mikrotik.jpeg">';
echo '</div>';
echo '</div>';
echo '<div class="u-container-style u-list-item u-repeater-item">';
echo '<div class="u-container-layout u-similar-container u-valign-top u-container-layout-2">';
echo '<img alt="" class="u-expanded-width-xs u-image u-image-contain u-image-default u-image-2" data-image-width="860" data-image-height="853" src="images/cisco.jpeg">';
echo '</div>';
echo '</div>';
echo '<div class="u-container-style u-list-item u-repeater-item">';
echo '<div class="u-container-layout u-similar-container u-valign-top u-container-layout-3">';
echo '<img alt="" class="u-expanded-width-xs u-image u-image-contain u-image-default u-image-3" data-image-width="343" data-image-height="147" src="images/oracle.jpeg">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<section class="u-clearfix u-section-4" id="sec-d9c7">';
echo '<div class="u-clearfix u-sheet u-sheet-1">';
echo '<h2 class="u-align-center u-text u-text-default u-text-1"> Fasilitas&nbsp;<span class="u-text-custom-color-2">SMK MADINATULQURAN:</span>';
echo '</h2>';
echo '<div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">';
echo '<div class="u-layout">';
echo '<div class="u-layout-col">';
echo '<div class="u-size-30">';
echo '<div class="u-layout-row">';
echo '<div class="u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-1">';
echo '<div class="u-container-layout u-container-layout-1"><span class="u-file-icon u-icon u-icon-1"><img src="images/916771.png" alt=""></span>';
echo '<h4 class="u-text u-text-custom-color-1 u-text-default u-text-2"> Smart School</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-align-right u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-2">';
echo '<div class="u-container-layout u-container-layout-2"><span class="u-align-center u-file-icon u-icon u-icon-2"><img src="images/1946488.png" alt=""></span>';
echo '<h4 class="u-align-center u-text u-text-custom-color-1 u-text-default u-text-3"> Asrama</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-3">';
echo '<div class="u-container-layout u-container-layout-3"><span class="u-file-icon u-icon u-icon-3"><img src="images/615579.png" alt=""></span>';
echo '<h4 class="u-text u-text-custom-color-1 u-text-default u-text-4"> Kelas AC</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-4">';
echo '<div class="u-container-layout u-container-layout-4"><span class="u-file-icon u-icon u-icon-4"><img src="images/921439.png" alt=""></span>';
echo '<h4 class="u-align-center u-text u-text-custom-color-1 u-text-default u-text-5"> Multimedia</h4>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="u-size-30">';
echo '<div class="u-layout-row">';
echo '<div class="u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-5">';
echo '<div class="u-container-layout u-container-layout-5"><span class="u-file-icon u-icon u-icon-5"><img src="images/159599.png" alt=""></span>';
echo '<h4 class="u-text u-text-custom-color-1 u-text-default u-text-6"> Wifi /Inter​net</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-6">';
echo '<div class="u-container-layout u-container-layout-6"><span class="u-file-icon u-icon u-icon-6"><img src="images/89014.png" alt=""></span>';
echo '<h4 class="u-text u-text-custom-color-1 u-text-default u-text-7"> Masjid</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-7">';
echo '<div class="u-container-layout u-container-layout-7"><span class="u-file-icon u-icon u-icon-7"><img src="images/706759.png" alt=""></span>';
echo '<h4 class="u-text u-text-custom-color-1 u-text-default u-text-8"> Saung Belajar</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-container-style u-layout-cell u-size-15 u-size-30-md u-layout-cell-8">';
echo '<div class="u-container-layout u-container-layout-8"><span class="u-file-icon u-icon u-icon-8"><img src="images/1165187.png" alt=""></span>';
echo '<h4 class="u-text u-text-custom-color-1 u-text-default u-text-9"> Lapangan</h4>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-bbeb"><div class="u-clearfix u-sheet u-valign-middle u-sheet-1">';
echo '<p class="u-small-text u-text u-text-variant u-text-1"> © Copyright Derrial Didhan Ekbar 2021&nbsp;All Right Reserved.</p>';
echo '</div></footer>';
echo '</body>';
echo '</html>';
?>